name: 'run'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: main
        env:
          LOG_LEVEL: INFO
          SCKEY: ${{ secrets.SCKEY }}
          SCTKEY: ${{ secrets.SCTKEY }}
          Skey: ${{ secrets.Skey }}
          Smode: ${{ secrets.Smode }}
          pushplus_token: ${{ secrets.pushplus_token }}
          pushplus_topic: ${{ secrets.pushplus_topic }}
          tg_token: ${{ secrets.tg_token }}
          tg_chatid: ${{ secrets.tg_chatid }}
          tg_api_host: ${{ secrets.tg_api_host }}
          cookie_smzdm: ${{ secrets.cookie_smzdm }}
          cookie_v2ex: ${{ secrets.cookie_v2ex }}
          cookie_u2: ${{ secrets.cookie_u2 }}
        run: |
          find . -type f -name "checkin.py" -exec pipenv run python3 {} \;
