name: 'run'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.9

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: main
        env:
          LOG_LEVEL: INFO
          GITHUB_NOTIFICATION: 1
          SCKEY: ${{ secrets.SCKEY }}
          SCTKEY: ${{ secrets.SCTKEY }}
          CP_KEY: ${{ secrets.CP_KEY }}
          CP_MODE: ${{ secrets.CP_MODE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_TOPIC: ${{ secrets.PUSH_PLUS_TOPIC }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHATID: ${{ secrets.TG_CHATID }}
          TG_API_HOST: ${{ secrets.TG_API_HOST }}
          COOKIE_SMZDM: ${{ secrets.COOKIE_SMZDM }}
          COOKIE_V2EX: ${{ secrets.COOKIE_V2EX }}
          COOKIE_U2: ${{ secrets.COOKIE_U2 }}
        run: |
          bash ./checkin.sh
